version: "3"

services:
  terraform:
    image: hashicorp/terraform:1.6
    volumes:
      - ./:/work
    env_file:
      - .env
  pike:
    image: jameswoolfenden/pike
    volumes:
      - ./:/work
  tflint:
    build:
      context: .
      dockerfile: ./docker/tflint/Dockerfile
    image: sample-terraform-tflint
    volumes:
      - ./:/work
    working_dir: /work
  python:
    image: python:3.12
    volumes:
      - ./:/work
    working_dir: /work
  docs:
    image: quay.io/terraform-docs/terraform-docs
    volumes:
      - ./:/work
    working_dir: /work
